# Generated by Django 3.0.5 on 2020-07-28 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('appointid', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=15)),
                ('result', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='posative',
            fields=[
                ('posativid', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=15)),
                ('result', models.CharField(max_length=30)),
                ('appoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='neagtive',
            fields=[
                ('negativeid', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=15)),
                ('result', models.CharField(max_length=30)),
                ('appoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='donor',
            fields=[
                ('donorid', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=15)),
                ('result', models.CharField(max_length=30)),
                ('posativefk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.posative')),
            ],
        ),
    ]
