# Generated by Django 3.0.5 on 2020-08-13 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posative',
            name='appoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possitive', to='appointment.appointment'),
        ),
    ]
