# Generated by Django 3.0.5 on 2020-08-13 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20200813_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='posativefk',
        ),
        migrations.AlterField(
            model_name='posative',
            name='appoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posative', to='appointment.appointment'),
        ),
    ]
