# Generated by Django 3.0.5 on 2020-08-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20200813_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='blood_group',
            field=models.CharField(default='', max_length=12),
        ),
    ]
