# Generated by Django 3.0.5 on 2020-08-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_appointment_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
    ]
